### PR TITLE
Bump version to v0.6

### PR DESCRIPTION
**Pull request by Gnimuc**
Hey @dourouc05, are you still using this package? @francescoalemanno have made some improvements in PR https://github.com/Gnimuc/Hungarian.jl/pull/15. I just want to make sure this new release won't break your code. :)

### CODE REVIEW

**Comment by dourouc05** [comment]
Thank you for thinking of me :)! Yes, I still use it, albeit performance is now slightly less relevant for me. I think it will break my code, though, but I have to test it. 

Just about the deprecation: I'm not sure https://github.com/Gnimuc/Hungarian.jl/blob/73b70bc048c7266dde5a8eeab6defaa6d6cba702/src/Munkres.jl#L1 is enough, as the mutating method is replaced by a nonmutating one, it's not a simple function call (the function call should be replaced by a variable assignment).

**Comment by francescoalemanno** [comment]
if you guys need an imitation of the old mutating method it suffices to:
1) from each row where there is an assigned position (a starred zero), subtract from the row the cost of that position
2) for each column subtract the minimum of the column 
3) go to step 1, until no changes

this algorithm given the optimal assignments and the cost matrix will produce the mutated matrix of the munkres algorithm

**Comment by dourouc05** [comment]
On my side, just removing the ! worked (no deprecation warning, no behaviour change as per my test suite). I'll just be waiting for the new version to be tagged so I can do so on my package :)!

**Comment by Gnimuc** [comment]
I dropped `munkres!` on this release and mentioned https://github.com/Gnimuc/Hungarian.jl/pull/16#issuecomment-595327104 in the commit log. Anyway, it's not hard to find the proper fix in this small package when the code is broken.

**Pull request merged**
